### ISSUE TITLE
Use custom exception when xyxymatch fails

### ISSUE THREAD

**Issue by braingram** [spacetelescope/stsci.stimage#33]
Similar to: https://github.com/spacetelescope/tweakwcs/issues/202

Both jwst and roman pipelines catch an exception that originates in this package:
https://github.com/spacetelescope/stsci.stimage/blob/14f9240589472535812e3417e00282d9ff5dfb6e/src/immatch/xyxymatch.c#L67

Using a custom exception (that subclasses `RuntimeError` to maintain backwards-compatibility) would allow the pipelines to catch this specific error without testing the error message.

**Comment by mcara** [comment]
Exception type is set here: https://github.com/spacetelescope/stsci.stimage/blob/14f9240589472535812e3417e00282d9ff5dfb6e/src/wrap/immatch/py_xyxymatch.c#L132. IMO it is not worth the effort to modify this code to do string parsing here and defining custom exceptions in C code.
